# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  template-create:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Installing coder"
          command: curl -L https://coder.com/install.sh | sh -s -- --version 2.3.3
      - run:
          name: "Log into coder"          
          command: coder login https://h3n6h248294qq.pit-1.try.coder.app --token gWtNi3D3do-7anWg5xqFptLSrpWwF1oWP
      - run:
          name: "Enter the directory"
          command: cd pre-template
      - run:
          name: "Create template"
          command: coder templates push


workflows:
  template-create-workflow:
    jobs:
      - template-create
