version: 2.1

parameters:
  template-tag:
    type: string
    default: "pre"
  coder-version:
    type: string
    default: "2.3.3"

jobs:
  template-create:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          key: coder-installation-<< pipeline.parameters.coder-version >>
      - run:
          name: "Installing coder"
          command: curl -L https://coder.com/install.sh | sh -s -- --version << pipeline.parameters.coder_version >> --prefix /usr
      - save_cache:
          key: coder-installation-<< pipeline.parameters.coder_version >>
          paths:
            -  /usr/bin/coder
      - run:
          name: "Log into coder"          
          command: coder login ${CODER_URL} --token ${CODER_TOKEN}
      - run:
          name: "Create template"
          command: |
            cd << pipeline.parameters.template-tag >>
            coder templates create --yes || coder templates push --yes

workflows:
  template-create:
    jobs:
      - template-create
