version: 2.1

parameters:
  template-tag:
    type: string
    default: "pre"
  coder-version:
    type: string
    default: "2.3.2"

jobs:
  template-create:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          key: coder-installation-<< pipeline.parameters.coder-version >>
      - run:
          name: "Check if coder exists"
          command: |
            if ! command -v coder &> /dev/null; then
              echo "Coder not found, installing..."
              curl -L https://coder.com/install.sh | sudo sh -s -- --version << pipeline.parameters.coder-version >> --prefix=$HOME
              echo "Coder installed successfully"
            else
              echo "Coder already exists"
            fi
      - save_cache:
          key: coder-installation-<< pipeline.parameters.coder-version >>
          paths:
            - $HOME/bin
      - run:
          name: "Log into coder"          
          command: coder login ${CODER_URL} --token ${CODER_TOKEN}
      - run:
          name: "Create template"
          command: |
            cd << pipeline.parameters.template-tag >>-template
            coder templates create --yes || coder templates push --yes

workflows:
  template-create:
    jobs:
      - template-create
